SET(TEST_OUTPUT ${TEST_DIR}/${TEST_NAME}.out)

SET(COMPARISON_FILE ${TEST_RESULT})

STRING(REPLACE "-le"           "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-be"           "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-compressed"   "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-uncompressed" "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-v4"           "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-5"            "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-7.3"          "" COMPARISON_FILE ${COMPARISON_FILE})
STRING(REPLACE "-hdf"          "" COMPARISON_FILE ${COMPARISON_FILE})

MESSAGE("${CMAKE_COMMAND} -E compare_files ${TEST_RESULT} ${TEST_REFERENCE_DIR}/${COMPARISON_FILE}")
EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_RESULT} ${TEST_REFERENCE_DIR}/${COMPARISON_FILE}
                RESULT_VARIABLE OUTPUT_COMPARE)

#MESSAGE(${OUTPUT_COMPARE})
IF (${OUTPUT_COMPARE} STREQUAL "0")
        MESSAGE("Success")
        EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT} ${TEST_RESULT})
        RETURN()
ENDIF()

MESSAGE("FAILURE")
