MESSAGE("${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}")
SET(TEST_REFERENCE ${TEST_REFERENCE_DIR}/${TEST_RESULT})
IF (WIN32)
    SET(TEST_REFERENCE_WIN ${CMAKE_CURRENT_BINARY_DIR}/${TEST_RESULT}-win)
    CONFIGURE_FILE(${TEST_REFERENCE} ${TEST_REFERENCE_WIN} NEWLINE_STYLE CRLF)
    SET(TEST_REFERENCE ${TEST_REFERENCE_WIN})
ENDIF()

EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE}
                RESULT_VARIABLE OUTPUT_COMPARE)

IF (WIN32)
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_REFERENCE_WIN})
ENDIF()

IF (${OUTPUT_COMPARE} STREQUAL "0")
    MESSAGE("Success")
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT})
    RETURN()
ENDIF()

MESSAGE("FAILURE")
