SET(TEST_OUTPUT ${TEST_DIR}/${TEST_NAME}.out)

MESSAGE("${CMAKE_COMMAND} -E compare_files ${TEST_RESULT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}")
EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_RESULT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}
                RESULT_VARIABLE OUTPUT_COMPARE)

MESSAGE(${OUTPUT_COMPARE})
IF (${OUTPUT_COMPARE} STREQUAL "0")
        MESSAGE("Success")
        EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT} ${TEST_RESULT})
        RETURN()
ENDIF()

MESSAGE("FAILURE")
